# node aliases and functions for development
alias nb='npm run build'
alias nd='npm run dev'
alias ndd='LOGGING_LEVEL=debug && npm run dev'
alias ndi='LOGGING_LEVEL=info && npm run dev'
alias nj='npm run test-dev'
alias njd='LOGGING_LEVEL=debug && npm run test-dev'
alias nji='LOGGING_LEVEL=info && npm run test-dev'
alias nl='npm run lint'
alias nsd='npm run start-dev'
alias nsdd='LOGGING_LEVEL=debug && npm run start-dev'
alias nsdi='LOGGING_LEVEL=info && npm run start-dev'
alias nsr='npm run start'
alias nsrd='LOGGING_LEVEL=debug && npm run start'
alias nsri='LOGGING_LEVEL=info && npm run start'
alias nt='npm run test'
alias ntd='LOGGING_LEVEL=debug && npm run test'
alias nti='LOGGING_LEVEL=info && npm run test'
