theme = "base16_transparent"

[editor]
line-number = "relative"
true-color = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[keys.normal.g]
q = ":reflow"

[keys.normal.space]
q = ":quit"
w = ":write"