theme = "ayu_dark"

[editor]
line-number = "relative"
true-color = true
mouse = false
bufferline = "multiple"
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.g]
q = ":reflow"

[keys.normal.space]
q = ":quit"
w = ":write"